apiVersion: v1
kind: Secret
metadata:
  name: harbor-replicator-secrets
  namespace: harbor-replicator
  labels:
    app: harbor-replicator
    component: secrets
type: Opaque
data:
  # Base64 encoded passwords (replace with actual base64 encoded values)
  # echo -n "your_password" | base64
  source-password: SGFyYm9yMTIzNDU=  # Harbor12345
  target-1-password: SGFyYm9yMTIzNDU=  # Harbor12345
  # Additional target passwords can be added here
  # target-2-password: base64_encoded_password
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-replicator-tls
  namespace: harbor-replicator
  labels:
    app: harbor-replicator
    component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (if TLS is enabled)
  # Replace with actual base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded private key